jaffle_shop:
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: kestra
      password: k3str4
      port: 5432
      dbname: kestra
      schema: public
      connect_timeout: 10
  target: dev
